### ISSUE TITLE
Face mask detection

### ISSUE THREAD

**Issue by akhil-debug** [geekquad/Image-Processing-OpenCV#152]
I am a GSSOC participant. I would like to work on a project that detects if a person is wearing a face mask and alerts the bystanders if there are a lot of people without face masks. Please assign this project to me.

**Comment by geekquad** [comment]
Hey @akhil-debug, we are focusing more on the implementation of Image Processing techniques rather than its application.
This repo is not for the accumulation of projects/mini-projects.
Please reopen the issue if I missed out on something. Do let me know if there is a specific Image Processing technique you will be using here!
